services:

  backend:
    build:
      context: ./backend
    container_name: ecommerce-backend
    ports:
      - "5000:5000"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: ecommerce-frontend
    ports:
      - "5173:5173"
    restart: unless-stopped
    depends_on:
      - backend
