apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce-frontend
  template:
    metadata:
      labels:
        app: ecommerce-frontend
    spec:
      containers:
        - name: frontend
          image: ecommerce-platform-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5173
          readinessProbe:
            tcpSocket:
              port: 5173
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5173
            initialDelaySeconds: 15
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-frontend
spec:
  selector:
    app: ecommerce-frontend
  ports:
    - port: 5173
      targetPort: 5173
  type: NodePort
